"""empty message

Revision ID: b1a57da9eccf
Revises: 8b2ffb9c901c
Create Date: 2022-02-24 23:54:28.332363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a57da9eccf'
down_revision = '8b2ffb9c901c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('personaje_id', sa.Integer(), nullable=True))
    op.add_column('usuario', sa.Column('planeta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuario', 'personaje', ['personaje_id'], ['id'])
    op.create_foreign_key(None, 'usuario', 'planeta', ['planeta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'planeta_id')
    op.drop_column('usuario', 'personaje_id')
    # ### end Alembic commands ###
